SECONDS_IN_MINUTE = 60
SECONDS_IN_HOUR = SECONDS_IN_MINUTE * 60
SECONDS_IN_DAY = SECONDS_IN_HOUR * 24
NOTIFICATION_NAME_STATUS = "STATUS"
NOTIFICATION_NAME_NEWS = "NEWS"
NOTIFICATION_NAME_MARKETING = "MARKETING"
